manager/urls.py
from django.urls import path
from .views import users_reservations


app_name = 'manager'
urlpatterns = [
    path('users_reservations', users_reservations, name='users_reservations'),
]

yummy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home.views import index
from django.conf.urls.static import static
from account.views import UserLogin, UserRegister, logout
from home.views import thanks
urlpatterns = [
    path('admin/', admin.site.urls),
    path('thanks/', thanks, name='thanks'),
    path('manager/', include('manager.urls')),

    path('', index, name='index'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', logout, name='logout'),
    path('register/', UserRegister.as_view(), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
<footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-3 col-md-6 d-flex">
          <i class="{{ footer_items.address.item_icon}}"></i>
          <div>
              
            <h4>{{ footer_items.address.item_title }}</h4>
            <p>
              {{ footer_items.address.item_description|safe }}
            </p>
          </div>

        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
           <i class="{{ footer_items.reservation.item_icon}}"></i>
          <div>
              
            <h4>{{ footer_items.reservation.item_title }}</h4>
            <p>
              {{ footer_items.reservation.item_description|safe }}
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Opening Hours</h4>
            <p>
              <strong>Mon-Sat: 11AM</strong> - 23PM<br>
              Sunday: Closed
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Follow Us</h4>
          <div class="social-links d-flex">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Yummy</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer>

templates/includes/header.html
 <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center me-auto me-lg-0">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>Yummy<span>.</span></h1>
      </a>
      {% include 'includes/nav.html' %}  
      <a class="btn-book-a-table" href="#book-a-table">Book a Table</a>
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header> 

templates/includes/nav.html
{% load is_manager_tag %}

<nav id="navbar" class="navbar">
    <ul>
        <li><a href="#menu">Menu</a></li>
        <li><a href="#events">Events</a></li>
        <li><a href="#chefs">Chefs</a></li>
        <li><a href="#gallery">Gallery</a></li>
        <li class="dropdown">
            <a href="#"><span>User</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Sign Out</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Sign In</a></li>
                    <li><a href="{% url 'register' %}">Register</a></li>
                {% endif %}
            </ul>
        </li>
        <li><a href="#contact">Contact</a></li>
       
        {% if user|is_manager_tag:"manager" %}
            <li><a href="{% url 'manager:users_reservations' %}">Manager</a></li>
        {% endif %}
    </ul>
</nav>